In [1]:
import torch
import numpy as np

### Torch Basics
- If there is an underscore then inplace operation
- Checking for GPU: torch.cuda.is_available()
- To move a tensor into CPU, tensor.to('cpu')
- To numpy: tensor.numpy(), from_numpy(), vice versa
- It tells pytorch that gradients are needed to be calculated: requires_grad=True


In [42]:
a = torch.rand(2,2) #zeros, ones
b = torch.rand(2,2)
print(a)
print(b)
print(a-b) # +, *, /, -
print(torch.tensor([1,2,3],dtype=torch.float32))

tensor([[0.1853, 0.6787],
        [0.8373, 0.9964]])
tensor([[0.8622, 0.3000],
        [0.5147, 0.9687]])
tensor([[-0.6770,  0.3788],
        [ 0.3225,  0.0277]])
tensor([1., 2., 3.])


## Autograd

In [41]:
x = torch.randn(3,requires_grad=True)
print(x)
y = x+2
print(y)
# z=y*y*2
z = (y+2).mean()
print(z)
z.backward() #dz/dx
print(x.grad)

tensor([ 0.9154,  0.4519, -0.8869], requires_grad=True)
tensor([2.9154, 2.4519, 1.1131], grad_fn=<AddBackward0>)
tensor(4.1601, grad_fn=<MeanBackward0>)
tensor([0.3333, 0.3333, 0.3333])


## Backpropagation

In [55]:
x = torch.tensor(1.0)
y = torch.tensor(2.0)
w = torch.tensor(1.0,requires_grad=True)

In [56]:
y_hat = x*w
loss = (y-y_hat)**2
print(loss)

tensor(1., grad_fn=<PowBackward0>)


In [57]:
loss.backward()
print(w.grad)

tensor(-2.)


## Implementing Gradient Descent

### Using Numpy

In [78]:
X = np.array([1,2,3],dtype=np.float32)
Y = np.array([2,3,4],dtype=np.float32)
w = 0 #weight initialization
def forward(X): #Model prediction
    return w*x.numpy()
def loss(y,y_pred): #Loss
    return ((y-y_pred)**2).mean()
#Loss = 1/N*(w*x - y_pred)**2
# Gradient/dw = 1/N 2x (w*x-y)
def gradient(x,y_pred,y): # We dont need this while Torch implementation
    return np.dot(2*x,y_pred-y).mean()

In [79]:
print(f'prediction before training',forward(X))

prediction before training 0.0


In [82]:
learning_rate = 0.01
epochs = 10

for i in range(epochs):
    print('epoch',i+1)
    y_pred = forward(X)
    print(y_pred)
    l=loss(Y,y_pred)
    dw = gradient(X,y_pred,Y)
    w-=dw*learning_rate



epoch 1
2.404996738433838
epoch 2
2.5163971519470216
epoch 3
2.6144294929504395
epoch 4
2.700697956085205
epoch 5
2.7766142082214356
epoch 6
2.8434205055236816
epoch 7
2.9022100448608397
epoch 8
2.953944845199585
epoch 9
2.999471454620361
epoch 10
3.039534883499145


### Using Torch
- Manual calculation of loss and optimizing gradients

In [90]:
X = torch.tensor([1,2,3],dtype=torch.float32)
Y = torch.tensor([2,3,4],dtype=torch.float32)
w = torch.tensor(0,dtype=torch.float32,requires_grad=True) #weight initialization
def forward(X): #Model prediction
    return w*x
def loss(y,y_pred): #Loss
    return ((y-y_pred)**2).mean()
#Loss = 1/N*(w*x - y_pred)**2
# Gradient/dw = 1/N 2x (w*x-y)
# def gradient(x,y_pred,y): # We dont need this while Torch implementation
#     return np.dot(2*x,y_pred-y).mean()

In [91]:
learning_rate = 0.01
epochs = 10

for i in range(epochs):
    print('epoch',i+1)
    y_pred = forward(X)
    print(y_pred)
    l=loss(Y,y_pred)
    l.backward()
    with torch.no_grad():
        w-=w.grad*learning_rate # We dont want gradient update to be a part of gradient calculations
    w.grad.zero_() # change the gradient back to 0



epoch 1
tensor(0., grad_fn=<MulBackward0>)
epoch 2
tensor(0.0600, grad_fn=<MulBackward0>)
epoch 3
tensor(0.1188, grad_fn=<MulBackward0>)
epoch 4
tensor(0.1764, grad_fn=<MulBackward0>)
epoch 5
tensor(0.2329, grad_fn=<MulBackward0>)
epoch 6
tensor(0.2882, grad_fn=<MulBackward0>)
epoch 7
tensor(0.3425, grad_fn=<MulBackward0>)
epoch 8
tensor(0.3956, grad_fn=<MulBackward0>)
epoch 9
tensor(0.4477, grad_fn=<MulBackward0>)
epoch 10
tensor(0.4988, grad_fn=<MulBackward0>)


### Using Torch
- Torch calculation of loss and optimizing gradients

In [94]:
X = torch.tensor([1,2,3],dtype=torch.float32)
Y = torch.tensor([2,3,4],dtype=torch.float32)
w = torch.tensor(0,dtype=torch.float32,requires_grad=True) #weight initialization
def forward(X): #Model prediction
    return w*x

import torch.nn as nn

learning_rate = 0.01

loss = nn.MSELoss()
optimizer = torch.optim.SGD([w],lr=learning_rate)

In [95]:
epochs = 10

for i in range(epochs):
    print('epoch',i+1)
    y_pred = forward(X)
    print(y_pred)
    l=loss(Y,y_pred)
    l.backward()
    optimizer.step()
    w.grad.zero_() # change the gradient back to 0



epoch 1
tensor(0., grad_fn=<MulBackward0>)
epoch 2
tensor(0.0600, grad_fn=<MulBackward0>)
epoch 3
tensor(0.1188, grad_fn=<MulBackward0>)
epoch 4
tensor(0.1764, grad_fn=<MulBackward0>)
epoch 5
tensor(0.2329, grad_fn=<MulBackward0>)
epoch 6
tensor(0.2882, grad_fn=<MulBackward0>)
epoch 7
tensor(0.3425, grad_fn=<MulBackward0>)
epoch 8
tensor(0.3956, grad_fn=<MulBackward0>)
epoch 9
tensor(0.4477, grad_fn=<MulBackward0>)
epoch 10
tensor(0.4988, grad_fn=<MulBackward0>)


/Users/prashant.singh/anaconda3/envs/pytorch/lib/python3.11/site-packages/torch/nn/modules/loss.py:536: UserWarning: Using a target size (torch.Size([])) that is different to the input size (torch.Size([3])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


### Using Torch
- Model building

In [127]:
import torch
import torch.nn as nn

X = torch.tensor([[1], [2], [3], [4]], dtype=torch.float32)
Y = torch.tensor([[2], [4], [6], [8]], dtype=torch.float32)

n_samples, n_features = X.shape

# 0) create a test sample

# 1) Design Model, the model has to implement the forward pass!
# Here we can use a built-in model from PyTorch
input_size = n_features
output_size = n_features

# we can call this model with samples X
model = nn.Linear(input_size, output_size)


In [132]:
epochs = 100
learning_rate=0.01

for i in range(epochs):
    print('epoch',i+1)
    y_pred = model(X)
    print(y_pred)
    l=loss(Y,y_pred)
    l.backward()
    optimizer.step()
    optimizer.zero_grad()
 # change the gradient back to 0
    
print(f'Prediction after training: f(5) = {model(X_test).item():.3f}')



epoch 1
tensor([[-0.1604],
        [-0.8795],
        [-1.5987],
        [-2.3178]], grad_fn=<AddmmBackward0>)
epoch 2
tensor([[-0.1604],
        [-0.8795],
        [-1.5987],
        [-2.3178]], grad_fn=<AddmmBackward0>)
epoch 3
tensor([[-0.1604],
        [-0.8795],
        [-1.5987],
        [-2.3178]], grad_fn=<AddmmBackward0>)
epoch 4
tensor([[-0.1604],
        [-0.8795],
        [-1.5987],
        [-2.3178]], grad_fn=<AddmmBackward0>)
epoch 5
tensor([[-0.1604],
        [-0.8795],
        [-1.5987],
        [-2.3178]], grad_fn=<AddmmBackward0>)
epoch 6
tensor([[-0.1604],
        [-0.8795],
        [-1.5987],
        [-2.3178]], grad_fn=<AddmmBackward0>)
epoch 7
tensor([[-0.1604],
        [-0.8795],
        [-1.5987],
        [-2.3178]], grad_fn=<AddmmBackward0>)
epoch 8
tensor([[-0.1604],
        [-0.8795],
        [-1.5987],
        [-2.3178]], grad_fn=<AddmmBackward0>)
epoch 9
tensor([[-0.1604],
        [-0.8795],
        [-1.5987],
        [-2.3178]], grad_fn=<AddmmBackward0>)
e